---
- name: Install Node Exporter on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - tar

    - name: Create directory for Node Exporter
      file:
        path: /opt/node_exporter
        state: directory
        mode: '0755'

    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/node_exporter
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Create a systemd service file for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/opt/node_exporter/node_exporter
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Set proper permissions for the systemd service file
      file:
        path: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Reload systemd daemon to apply new service
      command: systemctl daemon-reload

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started

    - name: Clean up downloaded Node Exporter tar file
      file:
        path: /tmp/node_exporter.tar.gz
        state: absent
